services:
  # ----------------------------------------
  # Angular 19 Frontend Service (Production)
  # ----------------------------------------
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod # Builds static files and serves with Nginx
    container_name: angular_frontend
    ports:
      # Host 4242 maps to Nginx container port 80
      - "4241:80"
    networks:
      - my_network

  # ----------------------------------------
  # Angular 19 Frontend Service (Development)
  # ----------------------------------------
  frontend-dev:
    extends: frontend
    build:
      target: dev # Overrides target to run 'ng serve'
    container_name: angular_frontend_dev
    ports:
      # Host 4200 maps to 'ng serve' container port 4200
      - "4200:4200"
    develop:
      # This section is used by 'docker compose watch'
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json

networks:
  my_network:
    driver: bridge
