name: CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    permissions:
      checks: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Make test.sh executable
        run: chmod +x test.sh

      - name: Set up Image Tags
        id: tags
        run: |
          # Sanitize branch name (replace non-alphanumeric/dot/dash with - and lowercase)
          BRANCH_NAME=$(echo "${{ github.ref_name }}" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-zA-Z0-9._-]/-/g')
          SHA_TAG="${{ github.sha }}"

          echo "image_version=${BRANCH_NAME}-${SHA_TAG}" >> $GITHUB_OUTPUT

      - name: Run test.sh
        env:
          DOCKER_BUILD_PARAMS: --cache-from=type=gha --cache-to=type=gha,mode=max --load
        run: ./test.sh "${{ steps.tags.outputs.image_version }}"

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          report_paths: "./test-results/*.xml"
          detailed_summary: true
          include_passed: true

      - name: Upload Test Artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: junit-test-results
          path: ./test-results/

  build:
    name: Build & Publish Image
    needs: test
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} # Jeton temporaire de l'App

      - name: Set up Image Tags
        id: tags
        run: |
          # Sanitize branch name (replace non-alphanumeric/dot/dash with - and lowercase)
          BRANCH_NAME=$(echo "${{ github.ref_name }}" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-zA-Z0-9._-]/-/g')
          SHA_TAG="${{ github.sha }}"
          IMAGE_BASE="ghcr.io/$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')"

          echo "image_name=${IMAGE_BASE}" >> $GITHUB_OUTPUT
          echo "image_version=${BRANCH_NAME}-${SHA_TAG}" >> $GITHUB_OUTPUT

      - name: Make build.sh executable
        run: chmod +x build.sh

      - name: Run build.sh
        env:
          DOCKER_BUILD_PARAMS: --cache-from=type=gha --cache-to=type=gha,mode=max --load
        run: ./build.sh "${{ steps.tags.outputs.image_name }}" "${{ steps.tags.outputs.image_version }}"

      - name: Push to GHCR
        run: |
          docker push "${{ steps.tags.outputs.image_name }}:${{ steps.tags.outputs.image_version }}"
